### ISSUE TITLE
Steam crashes while playing armsrace

### ISSUE THREAD

**Issue by ZippoKs** [zyhp/vac3_inhibitor#6]
Title explainst it, after about 1 minute of armsrace csgo freezes, can't be exitted (only task manager), and steam closes (csgo stays open)

Tested wingman yesterday, worked fine no crash.

**Comment by zyhp** [comment]
Most likely they added or changed something in a module and these changes made the crc32 change, since it is not in the known module list and you are using the Release version, it will close everything to prevent unknown behaviors.

Load the dll as Debug, get the unknown module, reverse by yourself and see if it is harmless or not, then add to the list based if it is not a telemetry module.
